//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GongChaWebSale.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chitietdh
    {
        public int madh { get; set; }
        public int masp { get; set; }
        public string size { get; set; }
        public int matp { get; set; }
        public Nullable<int> soluong { get; set; }
        public Nullable<int> thutu { get; set; }
        public Nullable<decimal> tongtiensp { get; set; }
    
        public virtual donhang donhang { get; set; }
        public virtual sanpham sanpham { get; set; }
        public virtual topping topping { get; set; }
    }
}
