//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GongChaWebSale.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETDH
    {
        public string MADH { get; set; }
        public string MAPC { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public Nullable<double> TONGTIENSP { get; set; }
    
        public virtual DONHANG DONHANG { get; set; }
        public virtual PHACHE PHACHE { get; set; }
    }
}
