//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GongChaWebSale.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class danhgia
    {
        public int madh { get; set; }
        public int matk { get; set; }
        public int masp { get; set; }
        public Nullable<System.DateTime> ngaydg { get; set; }
        public int sosao { get; set; }
        public string noidung { get; set; }
    
        public virtual donhang donhang { get; set; }
        public virtual sanpham sanpham { get; set; }
        public virtual taikhoan taikhoan { get; set; }
    }
}
