//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GongChaWebSale.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Database1Entities3 : DbContext
    {
        public Database1Entities3()
            : base("name=Database1Entities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<banggia> banggia { get; set; }
        public virtual DbSet<chitietdh> chitietdh { get; set; }
        public virtual DbSet<danhgia> danhgia { get; set; }
        public virtual DbSet<donhang> donhang { get; set; }
        public virtual DbSet<giohang> giohang { get; set; }
        public virtual DbSet<giohang_sanpham> giohang_sanpham { get; set; }
        public virtual DbSet<hoadon> hoadon { get; set; }
        public virtual DbSet<khuyenmai> khuyenmai { get; set; }
        public virtual DbSet<loaisp> loaisp { get; set; }
        public virtual DbSet<loaitk> loaitk { get; set; }
        public virtual DbSet<sanpham> sanpham { get; set; }
        public virtual DbSet<taikhoan> taikhoan { get; set; }
        public virtual DbSet<topping> topping { get; set; }
        public virtual DbSet<trangthaidonhang> trangthaidonhang { get; set; }
    }
}
