//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GongChaWebSale.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class giohang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public giohang()
        {
            this.giohang_sanpham = new HashSet<giohang_sanpham>();
        }
    
        public int magh { get; set; }
        public int matk { get; set; }
        public Nullable<System.DateTime> ngaytao { get; set; }
        public Nullable<decimal> tongtien { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<giohang_sanpham> giohang_sanpham { get; set; }
        public virtual taikhoan taikhoan { get; set; }
    }
}
