//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GongChaWebSale.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hoadon
    {
        public int mahd { get; set; }
        public int madh { get; set; }
        public Nullable<decimal> tongtien { get; set; }
        public Nullable<decimal> giamgia { get; set; }
        public Nullable<decimal> thanhtien { get; set; }
        public int matk { get; set; }
    
        public virtual donhang donhang { get; set; }
        public virtual taikhoan taikhoan { get; set; }
    }
}
