//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GongChaWebSale.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class khuyenmai
    {
        public string makm { get; set; }
        public int masp { get; set; }
        public string size { get; set; }
        public System.DateTime ngaybatdau { get; set; }
        public System.DateTime ngayketthuc { get; set; }
        public decimal phantramgiam { get; set; }
        public string tenkm { get; set; }
        public string noidung { get; set; }
    
        public virtual banggia banggia { get; set; }
        public virtual sanpham sanpham { get; set; }
    }
}
