//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GongChaWebSale.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHACHE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHACHE()
        {
            this.CHITIETDHs = new HashSet<CHITIETDH>();
        }
    
        public string MAPC { get; set; }
        public string MASP { get; set; }
        public string MATP { get; set; }
        public Nullable<int> SOLUONTP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDH> CHITIETDHs { get; set; }
        public virtual SP SP { get; set; }
        public virtual Topping_ Topping_ { get; set; }
    }
}
